#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Small shared UI snippets used across chat pages."""

import streamlit as st

# One place to edit the wording of the general AI caveat.
AI_NOTE = (
    "⚠️ Replies are generated by an AI and can be **wrong or made up** "
    '("hallucinated"). Treat them as a simulation, and check anything important '
    "against a reliable source."
)


def ai_note():
    """A concise caption reminding students the AI can be incorrect."""
    st.caption(AI_NOTE)
